// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4jYWdFaUu6bkihAzBMDO_Mb_6d5w-Fcc',
    appId: '1:954206993249:web:bae7a415c57e3f2ecae320',
    messagingSenderId: '954206993249',
    projectId: 'kigali-guiders',
    authDomain: 'kigali-guiders.firebaseapp.com',
    storageBucket: 'kigali-guiders.firebasestorage.app',
    measurementId: 'G-YMTP34EWH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiIjlmXDFgfpQy8awl7J7NZIgMmY0LBQ',
    appId: '1:954206993249:android:1b3f28b0e4547081cae320',
    messagingSenderId: '954206993249',
    projectId: 'kigali-guiders',
    storageBucket: 'kigali-guiders.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8SghlTZVDn8ZqFEt5lYIOXA5k8bh_GU',
    appId: '1:954206993249:ios:2631e64a95cbc0dbcae320',
    messagingSenderId: '954206993249',
    projectId: 'kigali-guiders',
    storageBucket: 'kigali-guiders.firebasestorage.app',
    iosBundleId: 'com.example.kigaliGuider',
  );
}
